import { useMemo, useRef, useState } from "react";
import type { ChangeEvent, DragEvent, ReactNode } from "react";
import { AlertTriangle, ArrowDownToLine, BarChart3, Check, CheckCircle2, ChevronRight, Database, FileSpreadsheet, FileUp, History, LogIn, Search, Settings2, ShieldAlert, ShieldCheck, Sparkles, Upload, User, WandSparkles, X } from "lucide-react";
import { analyzeRows, calculateScore, createProfile, escapeCsv, parseCsv } from "@/lib/quality.mjs";

type Row = Record<string, string>;
type IssueType = "Duplicate ID" | "Duplicate email" | "Invalid email" | "Missing value" | "Invalid type" | "Sensitive data";
type Issue = { row: number; field: string; value: string; type: IssueType; message: string; severity: "high" | "medium" | "low" };
type Rules = { required: boolean; uniqueId: boolean; email: boolean; numeric: boolean; pii: boolean };
type Run = { id: string; fileName: string; date: string; rows: number; score: number; issues: number };
type AuthUser = { id: string; email: string; role: "admin" | "reviewer" };
type RuleSet = { id: string; name: string; rules: Rules; schema: { idField: string; emailField: string }; piiPatterns: string[] };

const sample = `customer_id,full_name,email,age,department\n1001,Ada Lovelace,ada@analytical.org,36,Engineering\n1002,Grace Hopper,grace.hopper@navy.mil,85,Engineering\n1003,Alan Turing,alan.turing.example,41,Research\n1001,Katherine Johnson,katherine@nasa.gov,101,Research\n1005,,marie@curie.org,66,Science\n1006,Linus Torvalds,grace.hopper@navy.mil,55,Engineering`;
const apiBaseUrl = import.meta.env.VITE_API_BASE_URL || "http://localhost:8787";

function readHistory(): Run[] {
  try { return JSON.parse(localStorage.getItem("dia-runs") || "[]"); }
  catch { return []; }
}

function readSession(): { token: string; user: AuthUser } | null {
  try { return JSON.parse(localStorage.getItem("dia-session") || "null"); }
  catch { return null; }
}

export default function App() {
  const input = useRef<HTMLInputElement>(null);
  const [fileName, setFileName] = useState(""); const [rows, setRows] = useState<Row[]>([]);
  const [idField, setIdField] = useState(""); const [emailField, setEmailField] = useState("");
  const [rules, setRules] = useState<Rules>({ required: true, uniqueId: true, email: true, numeric: false, pii: true });
  const [filter, setFilter] = useState<IssueType | "All">("All"); const [query, setQuery] = useState("");
  // Validation history is deliberately local: uploaded data never leaves the browser.
  const [history, setHistory] = useState<Run[]>(readHistory); const [activeTab, setActiveTab] = useState<"issues" | "profile" | "history">("issues");
  const [session, setSession] = useState<{ token: string; user: AuthUser } | null>(readSession);
  const [email, setEmail] = useState("admin@example.com"); const [password, setPassword] = useState("demo-admin"); const [authMessage, setAuthMessage] = useState("");
  const [ruleSets, setRuleSets] = useState<RuleSet[]>([]); const [ruleSetName, setRuleSetName] = useState(""); const [piiPatterns, setPiiPatterns] = useState("");
  const headers = useMemo(() => rows[0] ? Object.keys(rows[0]) : [], [rows]);

  const issues = useMemo<Issue[]>(() => analyzeRows(rows, { headers, idField, emailField, rules, piiPatterns }) as Issue[], [rows, headers, idField, emailField, rules, piiPatterns]);
  // Weighting lets a duplicate ID reduce trust more than an advisory PII flag.
  const score = useMemo(() => calculateScore(rows.length, issues), [rows.length, issues]);
  const profile = useMemo(() => createProfile(rows, headers) as { field: string; type: string; completeness: number; unique: number; samples: string }[], [headers, rows]);
  const visibleIssues = issues.filter((issue) => (filter === "All" || issue.type === filter) && `${issue.field} ${issue.value} ${issue.message}`.toLowerCase().includes(query.toLowerCase()));
  const count = (type: IssueType) => issues.filter((issue) => issue.type === type).length;
  const issueBreakdown = (["Duplicate ID", "Duplicate email", "Invalid email", "Missing value", "Invalid type", "Sensitive data"] as IssueType[]).map((type) => ({ type, value: count(type) })).filter((item) => item.value > 0);

  function load(text: string, name: string) { const nextRows = parseCsv(text); const nextHeaders = nextRows[0] ? Object.keys(nextRows[0]) : []; setRows(nextRows); setFileName(name); setIdField(nextHeaders.find((header) => /(^|[_\s-])id$/i.test(header)) || ""); setEmailField(nextHeaders.find((header) => /e-?mail/i.test(header)) || ""); setFilter("All"); setActiveTab("issues"); }
  function upload(file?: File) { if (!file || !file.name.toLowerCase().endsWith(".csv")) return; const reader = new FileReader(); reader.onload = () => load(String(reader.result), file.name); reader.readAsText(file); }
  async function loadRuleSets(token: string) { try { const response = await fetch(`${apiBaseUrl}/api/rule-sets`, { headers: { Authorization: `Bearer ${token}` } }); if (response.ok) setRuleSets(await response.json()); } catch { /* Offline API is handled when a user saves a ruleset. */ } }
  async function signIn() { try { setAuthMessage("Signing in…"); const response = await fetch(`${apiBaseUrl}/api/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Unable to sign in"); setSession(result); localStorage.setItem("dia-session", JSON.stringify(result)); await loadRuleSets(result.token); setAuthMessage(""); } catch (error) { setAuthMessage(error instanceof Error ? error.message : "Unable to sign in"); } }
  function signOut() { setSession(null); localStorage.removeItem("dia-session"); }
  async function saveRun() { if (!rows.length) return; const run = { id: crypto.randomUUID(), fileName, date: new Date().toLocaleString(), rows: rows.length, score, issues: issues.length }; const next = [run, ...history].slice(0, 10); setHistory(next); localStorage.setItem("dia-runs", JSON.stringify(next)); if (session) { try { const response = await fetch(`${apiBaseUrl}/api/datasets`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.token}` }, body: JSON.stringify({ name: fileName, rows: rows.length, summary: { score, issues: issues.length, rules } }) }); if (!response.ok) throw new Error("API save failed"); setAuthMessage("Run saved to local history and API audit log."); } catch { setAuthMessage("Saved locally. Start the API to persist this run remotely."); } } else setAuthMessage("Saved locally. Sign in to add this run to the API audit log."); setActiveTab("history"); }
  async function saveRuleSet() { if (!session || !ruleSetName.trim()) return; try { const response = await fetch(`${apiBaseUrl}/api/rule-sets`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.token}` }, body: JSON.stringify({ name: ruleSetName.trim(), rules, schema: { idField, emailField }, piiPatterns: piiPatterns.split(",").map((value) => value.trim()).filter(Boolean) }) }); if (!response.ok) throw new Error(); setRuleSetName(""); await loadRuleSets(session.token); setAuthMessage("Ruleset saved to the API."); } catch { setAuthMessage("Could not save ruleset. Start the API and sign in first."); } }
  function applyRuleSet(ruleSet: RuleSet) { setRules(ruleSet.rules); setIdField(ruleSet.schema.idField); setEmailField(ruleSet.schema.emailField); setPiiPatterns(ruleSet.piiPatterns.join(", ")); setAuthMessage(`Applied “${ruleSet.name}”.`); }
  // A clean export excludes only high-severity rows so users can safely review
  // advisory findings without silently discarding data.
  function exportFile(clean = false) { const data: Row[] = clean ? rows.filter((_, index) => !issues.some((issue) => issue.row === index + 2 && issue.severity === "high")) : issues.map((issue) => ({ row: String(issue.row), field: issue.field, value: issue.value, issue: issue.type, details: issue.message })); const columns = clean ? headers : ["row", "field", "value", "issue", "details"]; const csv = [columns.join(","), ...data.map((record) => columns.map((field) => escapeCsv(record[field] || "")).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = clean ? "cleaned-data.csv" : "data-quality-issues.csv"; link.click(); URL.revokeObjectURL(link.href); }
  function normalize() { setRows((current) => current.map((row) => Object.fromEntries(Object.entries(row).map(([field, value]) => [field, field === emailField ? value.trim().toLowerCase() : value.trim()])))); }
  const toggle = (rule: keyof Rules) => setRules((current) => ({ ...current, [rule]: !current[rule] }));

  return <div className="min-h-screen bg-[#f7f8fc] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-white"><ShieldCheck size={20} /></div><span className="font-semibold tracking-tight">Data Integrity <span className="text-indigo-600">Analyzer</span></span></div><div className="flex items-center gap-3">{session ? <><span className="hidden text-sm text-slate-500 sm:block"><User className="mr-1 inline" size={14} />{session.user.email} · {session.user.role}</span><button onClick={signOut} className="text-sm font-medium text-slate-600 hover:text-slate-900">Sign out</button></> : <span className="hidden text-sm text-slate-500 sm:block">Trusted data, ready for decisions</span>}</div></div></header>
    <main className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold tracking-widest text-indigo-600">DATA QUALITY & AI READINESS</p><h1 className="text-3xl font-bold tracking-tight">Know whether your data is trustworthy</h1><p className="mt-2 text-slate-500">Profile, validate, and remediate CSV data before it powers a decision or AI workflow.</p></div>{rows.length > 0 && <button onClick={() => input.current?.click()} className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium shadow-sm hover:bg-slate-50"><Upload size={16} /> Upload another file</button>}</div><input ref={input} className="hidden" type="file" accept=".csv,text/csv" onChange={(event: ChangeEvent<HTMLInputElement>) => upload(event.target.files?.[0])} />
      {!rows.length ? <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><section onDragOver={(event) => event.preventDefault()} onDrop={(event: DragEvent<HTMLDivElement>) => { event.preventDefault(); upload(event.dataTransfer.files[0]); }} className="rounded-2xl border-2 border-dashed border-indigo-200 bg-white px-6 py-16 text-center shadow-sm"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><FileUp size={27} /></div><h2 className="mt-5 text-xl font-semibold">Drop your CSV file here</h2><p className="mt-2 text-sm text-slate-500">Run configurable quality and AI-readiness checks entirely in your browser.</p><button onClick={() => input.current?.click()} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white hover:bg-indigo-700"><Upload size={16} /> Select CSV file</button><button onClick={() => load(sample, "sample-customer-data.csv")} className="mt-6 block w-full text-sm font-medium text-indigo-600">Try sample data <ChevronRight className="inline" size={15} /></button></section>{!session && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><LogIn className="text-indigo-600" size={19} /><h2 className="font-semibold">Demo sign in</h2></div><p className="mt-2 text-sm text-slate-500">Save validation runs to the persistent audit API.</p><label className="field-label mt-5">Email<input value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="field-label mt-3">Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button onClick={signIn} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><LogIn size={15} /> Sign in</button><p className="mt-3 text-xs text-slate-500">Admin demo credentials are prefilled.</p>{authMessage && <p className="mt-3 text-xs text-rose-600">{authMessage}</p>}</section>}</div> : <>
        <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><FileSpreadsheet size={20} /></div><div><p className="font-semibold">{fileName}</p><p className="text-sm text-slate-500">{rows.length.toLocaleString()} records · {headers.length} columns · Browser-only analysis</p></div></div><div className="flex flex-wrap gap-2"><button onClick={normalize} className="tool-button"><WandSparkles size={15} /> Normalize values</button><button onClick={() => exportFile(true)} className="tool-button"><ArrowDownToLine size={15} /> Export clean rows</button><button onClick={saveRun} className="tool-button"><History size={15} /> Save run</button><button onClick={() => { setRows([]); setFileName(""); }} className="tool-button text-slate-500"><X size={15} /> Remove</button></div></div></section>
        <section className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><ScoreCard label="Trust score" value={`${score}/100`} icon={score >= 80 ? CheckCircle2 : AlertTriangle} tone={score >= 80 ? "emerald" : "amber"} hint={score >= 80 ? "Ready for review" : "Needs attention"} /><ScoreCard label="Total issues" value={issues.length} icon={AlertTriangle} tone="rose" hint={`${count("Duplicate ID") + count("Duplicate email")} duplicate conflicts`} /><ScoreCard label="Completeness" value={`${profile.length ? Math.round(profile.reduce((total, field) => total + field.completeness, 0) / profile.length) : 0}%`} icon={Database} tone="sky" hint="Across all fields" /><ScoreCard label="AI readiness" value={rules.pii ? `${count("Sensitive data")} flags` : "Not checked"} icon={Sparkles} tone="violet" hint="Potential sensitive data" /></section>
        <div className="mb-5 flex gap-2 border-b border-slate-200"><Tab active={activeTab === "issues"} onClick={() => setActiveTab("issues")} icon={ShieldAlert} label="Issues" /><Tab active={activeTab === "profile"} onClick={() => setActiveTab("profile")} icon={Database} label="Data profile" /><Tab active={activeTab === "history"} onClick={() => setActiveTab("history")} icon={History} label="Run history" /></div>
        {activeTab === "issues" && <><section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="flex items-center gap-2 font-semibold"><Settings2 size={17} /> Validation configuration</h2><p className="mt-1 text-sm text-slate-500">Map semantic fields and choose the rules to run.</p></div><div className="grid gap-2 sm:grid-cols-2 lg:flex"><label className="field-label">ID field<select value={idField} onChange={(event) => setIdField(event.target.value)}><option value="">Not mapped</option>{headers.map((header) => <option key={header}>{header}</option>)}</select></label><label className="field-label">Email field<select value={emailField} onChange={(event) => setEmailField(event.target.value)}><option value="">Not mapped</option>{headers.map((header) => <option key={header}>{header}</option>)}</select></label></div></div><div className="mt-4 flex flex-wrap gap-2">{([ ["required", "Required values"], ["uniqueId", "Unique IDs"], ["email", "Email validation"], ["numeric", "Numeric types"], ["pii", "PII detection"] ] as [keyof Rules, string][]).map(([rule, label]) => <button key={rule} onClick={() => toggle(rule)} className={`rounded-full px-3 py-1.5 text-xs font-medium ${rules[rule] ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-500"}`}>{rules[rule] && <Check className="mr-1 inline" size={12} />}{label}</button>)}</div><div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 lg:grid-cols-[1fr_auto]"><label className="field-label">Custom PII regular expressions (comma-separated)<input value={piiPatterns} onChange={(event) => setPiiPatterns(event.target.value)} placeholder="e.g. employee-\\d+, account:\\s*\\d+" /></label>{session && <div className="flex items-end gap-2"><input value={ruleSetName} onChange={(event) => setRuleSetName(event.target.value)} placeholder="Ruleset name" className="h-9 rounded-lg border border-slate-200 px-2 text-sm" /><button onClick={saveRuleSet} className="tool-button"><Check size={15} /> Save ruleset</button></div>}</div>{ruleSets.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{ruleSets.map((ruleSet) => <button key={ruleSet.id} onClick={() => applyRuleSet(ruleSet)} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-indigo-50 hover:text-indigo-700">Apply: {ruleSet.name}</button>)}</div>}</section>
          <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold">Detected issues</h2><p className="mt-1 text-sm text-slate-500">High-severity rows are excluded when exporting clean data.</p></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search issues" className="h-9 rounded-lg border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-indigo-400" /></label><button onClick={() => exportFile()} className="tool-button bg-slate-900 text-white"><ArrowDownToLine size={15} /> Export</button></div></div><div className="flex gap-2 overflow-x-auto border-b border-slate-100 px-5 py-3">{(["All", "Duplicate ID", "Duplicate email", "Invalid email", "Missing value", "Invalid type", "Sensitive data"] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-medium ${filter === item ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-600"}`}>{item}{item !== "All" && ` · ${count(item)}`}</button>)}</div><IssueTable issues={visibleIssues} /></section></>}
        {activeTab === "profile" && <><section className="mb-6 grid gap-6 lg:grid-cols-2"><ChartPanel title="Issues by validation type" icon={BarChart3}>{issueBreakdown.length ? <div className="space-y-4">{issueBreakdown.map((item) => <MetricBar key={item.type} label={item.type} value={item.value} maximum={Math.max(...issueBreakdown.map((entry) => entry.value))} tone="rose" />)}</div> : <ChartEmpty text="No issues detected for the current rule set." />}</ChartPanel><ChartPanel title="Column completeness" icon={Database}><div className="space-y-4">{profile.map((column) => <MetricBar key={column.field} label={column.field} value={column.completeness} maximum={100} suffix="%" tone={column.completeness === 100 ? "emerald" : "amber"} />)}</div></ChartPanel></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold">Column profile</h2><p className="mt-1 text-sm text-slate-500">Automatic type inference, completeness, uniqueness, and example values.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Field</th><th className="px-5 py-3">Inferred type</th><th className="px-5 py-3">Completeness</th><th className="px-5 py-3">Unique values</th><th className="px-5 py-3">Examples</th></tr></thead><tbody>{profile.map((column) => <tr key={column.field} className="border-t border-slate-100"><td className="px-5 py-3 font-medium">{column.field}</td><td className="px-5 py-3"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs text-indigo-700">{column.type}</span></td><td className="px-5 py-3"><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-emerald-500" style={{ width: `${column.completeness}%` }} /></div>{column.completeness}%</div></td><td className="px-5 py-3 text-slate-600">{column.unique}</td><td className="max-w-72 truncate px-5 py-3 text-slate-500">{column.samples}</td></tr>)}</tbody></table></div></section></>}
        {activeTab === "history" && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold">Validation history</h2><p className="mt-1 text-sm text-slate-500">{session ? "Saved runs are also sent to the authenticated API audit trail." : "Saved locally in this browser. Sign in to persist runs remotely."}</p>{authMessage && <p className="mt-2 text-sm text-indigo-600">{authMessage}</p>}</div>{history.length ? <div className="divide-y divide-slate-100">{history.map((run) => <div key={run.id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-medium">{run.fileName}</p><p className="mt-1 text-sm text-slate-500">{run.date} · {run.rows} records · {run.issues} issues</p></div><span className={`rounded-full px-3 py-1 text-sm font-semibold ${run.score >= 80 ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{run.score}/100</span></div>)}</div> : <Empty icon={History} title="No saved runs yet" text="Save a completed analysis to create an audit history." />}</section>}
      </>}</main></div>;
}

function ScoreCard({ label, value, icon: Icon, tone, hint }: { label: string; value: string | number; icon: typeof CheckCircle2; tone: "emerald" | "amber" | "rose" | "sky" | "violet"; hint: string }) { const colors = { emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", rose: "bg-rose-50 text-rose-600", sky: "bg-sky-50 text-sky-600", violet: "bg-violet-50 text-violet-600" }; return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><p className="text-sm font-medium text-slate-500">{label}</p><div className={`rounded-lg p-2 ${colors[tone]}`}><Icon size={17} /></div></div><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></div>; }
function Tab({ active, onClick, icon: Icon, label }: { active: boolean; onClick: () => void; icon: typeof Database; label: string }) { return <button onClick={onClick} className={`flex items-center gap-2 border-b-2 px-3 py-3 text-sm font-medium ${active ? "border-indigo-600 text-indigo-600" : "border-transparent text-slate-500"}`}><Icon size={16} />{label}</button>; }
function Empty({ icon: Icon, title, text }: { icon: typeof History; title: string; text: string }) { return <div className="px-6 py-14 text-center"><Icon className="mx-auto text-slate-300" size={32} /><p className="mt-3 font-medium">{title}</p><p className="mt-1 text-sm text-slate-500">{text}</p></div>; }
function ChartPanel({ title, icon: Icon, children }: { title: string; icon: typeof BarChart3; children: ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-semibold"><Icon size={17} className="text-indigo-600" />{title}</h2><div className="mt-5">{children}</div></section>; }
function ChartEmpty({ text }: { text: string }) { return <div className="grid h-48 place-items-center text-center text-sm text-slate-500">{text}</div>; }
function MetricBar({ label, value, maximum, suffix = "", tone }: { label: string; value: number; maximum: number; suffix?: string; tone: "emerald" | "amber" | "rose" }) { const colors = { emerald: "bg-emerald-500", amber: "bg-amber-500", rose: "bg-rose-500" }; return <div><div className="mb-1.5 flex justify-between gap-3 text-sm"><span className="truncate text-slate-600">{label}</span><span className="font-semibold text-slate-800">{value}{suffix}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${colors[tone]}`} style={{ width: `${Math.max(4, (value / Math.max(maximum, 1)) * 100)}%` }} /></div></div>; }
function IssueTable({ issues }: { issues: Issue[] }) { return issues.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Row</th><th className="px-5 py-3">Field</th><th className="px-5 py-3">Value</th><th className="px-5 py-3">Issue</th><th className="px-5 py-3">Recommended action</th></tr></thead><tbody>{issues.map((issue, index) => <tr key={`${issue.row}-${issue.field}-${issue.type}-${index}`} className="border-t border-slate-100"><td className="px-5 py-3 text-slate-500">{issue.row}</td><td className="px-5 py-3 font-medium">{issue.field}</td><td className="max-w-44 truncate px-5 py-3 text-slate-600">{issue.value}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${issue.severity === "high" ? "bg-rose-50 text-rose-700" : issue.severity === "medium" ? "bg-amber-50 text-amber-700" : "bg-sky-50 text-sky-700"}`}>{issue.type}</span></td><td className="px-5 py-3 text-slate-500">{issue.type === "Invalid email" ? "Correct or remove the address" : issue.type.includes("Duplicate") ? "Review matching records and merge or retain one" : issue.type === "Sensitive data" ? "Classify, mask, or restrict this value" : issue.message}</td></tr>)}</tbody></table></div> : <Empty icon={CheckCircle2} title="No matching issues" text="The selected validation rules found no matching issues." />; }
